import Head from "next/head";
import Main from "../components/Main";
import Navbar from "../components/common/Navbar";
import AboutArea from "../components/AboutArea";
import ContactUs from "../components/ContactUs";
import AllSkills from "../components/AllSkills";
import ProjectPortfolio from "../components/ProjectPortfolio";
import Footer from "../components/common/Footer";
export default function Home() {
  return (
    <div>
      <Head>
        <title>zayed_portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <AboutArea />
      <AllSkills />
      <ProjectPortfolio />
      <ContactUs />
      <Footer/>
    </div>
  );
}
